# Generated by Django 5.0 on 2023-12-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Vendedor',
        ),
    ]
